### PR TITLE
Implement DataValueInterfaces definitions

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
Bump

**Comment by davidanthoff** [comment]
I'm completely swamped through the end of next week and won't be able to engage on this until then. I'll try to follow up then, but if I forget, feel free to bump again :)

**Comment by quinnj** [comment]
Bump again

**Comment by davidanthoff** [comment]
I'll have some time this week to look at this!

**Comment by quinnj** [comment]
@davidanthoff, I've updated this PR to point to https://github.com/JuliaData/AbstractDataValues.jl (happy to move the package to Queryverse if you'd like; I'm not sure it really matters where it lives, as long as we both have admin access).

One thing I realized from what we talked about: having DataValues overload `Base.nonmissingtype` doesn't quite achieve the same purpose as `nondatavaluetype` because we're really looking for the `Union{T, Missing}` equivalent of `DataValue{T}` (and vice-versa for `datavaluetype`), which conflicts with the purpose of `Base.nonmissingtype`, which is to get the `T` from `Union{T, Missing}` (so the equivalent DataValue definition would be `Base.nonmissingtype(::Type{DataValue{T}}) where {T} = T`). I also left `unwrap` in for now as I haven't tested moving things over to using convert. I'll give that a shot and report back if we can remove it, but wanted to ping you on the initial setup here first.

**Comment by davidanthoff** [comment]
Cool!

I think it might make slightly more sense to host the package in queryverse? That way the two DataValue packages would be close together. But I also don't feel strongly about it. Oh, the one (really not very important) benefit would be that it would show up at https://www.queryverse.org/status/.

Should we maybe call the package DataValuesInterface.jl? `Abstract` to me implies a type, which we don't really have in that package?

re `nondatavaluetype`, yep, I see your point. I have two unrelated thoughts on that: a) should it be called `missingtype`, to be symmetric with `datavaluetype`? Maybe that is slightly more specific, by telling a user what they will get? b) I wonder whether this could still be folded into something existing, though... Maybe something like `convert(Union{nonmissingtype(typeof(x)), Missing}, typeof(x)`? But that is probably an abuse of `convert`... And maybe we should also not let the perfect be the enemy of the working in this case...

Re `unwrap`, yes, lets see whether you can get rid of that somehow. There is also `x[]` that unwraps, not sure whether that might also work?

One other random thought: the whole exercise does start to feel a little like defining an interface for different missing types... Probably not where we want to go?

**Comment by quinnj** [comment]
Sounds good. Could you create the repo in Queryverse org then and then add me as (at least) a collaborator? Then I can do the initial setup and update the PR here.

**Comment by quinnj** [comment]
Ok, I've pushed all the code for new DataValueInterfaces.jl: https://github.com/queryverse/DataValueInterfaces.jl. Tables.jl PR is [here](https://github.com/JuliaData/Tables.jl/pull/104). I'll add some tests here.

**Comment by davidanthoff** [comment]
Looks good. I probably have to trigger the registration of DataValueInterfaces? Let me know when you are ready with all the rest, and then I'll trigger the registration, and then we can merge this here.

**Comment by quinnj** [comment]
I think we're ready; let's trigger DataValueInterfaces.jl registration and I'll do a little more stress-testing on Tables.jl in the mean time.

**Comment by davidanthoff** [comment]
https://github.com/JuliaRegistries/General/pull/1630

**Comment by davidanthoff** [comment]
@quinnj I just restarted tests, and I think they are missing a `using DataValueInterfaces`?

**Comment by quinnj** [comment]
Alright, let's see how this goes (everything passes on my machine)

**Comment by quinnj** [comment]
Ok, tests look good here. Once we merge and tag a release here, I can re-run tests [here](https://github.com/JuliaData/Tables.jl/pull/104) and merge/tag there. Getting close!

**Comment by davidanthoff** [comment]
https://github.com/JuliaRegistries/General/pull/1708

**Pull request merged**
